CREATE DATABASE project3_sales;
USE project3_sales;
SELECT * FROM `data analytics dataset`;
SELECT count(*) AS total_records FROM `data analytics dataset`;
SELECT sum(TOTALPRICE) AS total_sales_revenue FROM `data analytics dataset`;
SELECT count(OrderID) AS total_orders FROM `data analytics dataset`;
SELECT avg(TotalPrice) AS average_order_value FROM `data analytics dataset`;
SELECT PaymentMethod, count(orderID) AS number_of_orders FROM `data analytics dataset` group by PaymentMethod;
SELECT PaymentMethod, sum(TotalPrice) AS total_revenue FROM `data analytics dataset` group by PaymentMethod;
SELECT OrderStatus, count(OrderID) AS number_of_orders FROM `data analytics dataset` group by OrderStatus;
SELECT OrderStatus, sum(TotalPrice) AS total_revenue FROM `data analytics dataset` group by OrderStatus;
SELECT Product, sum(Quantity) AS total_quantity_sold FROM `data analytics dataset` group by Product order by total_quantity_sold desc;
SELECT Product, sum(TotalPrice) AS total_revenue FROM `data analytics dataset` group by Product order by total_revenue DESC;
SELECT Product, avg(UnitPrice) AS average_unit_price FROM `data analytics dataset` group by Product order by average_unit_price DESC;
SELECT CustomerID, sum(TotalPrice) AS total_spent FROM `data analytics dataset` group by CustomerID order by total_spent DESC limit 10;
SELECT month(Date) AS sales_month, count(OrderID) AS monthly_orders FROM `data analytics dataset` group by month(Date) order by sales_month;
SELECT Date, sum(TotalPrice) AS daily_revenue FROM `data analytics dataset` group by Date order by daily_revenue DESC LIMIT 10;
SELECT count(*) AS total_rows, count(OrderID) AS order_id_count, count(CustomerID) AS customer_id_count, count(Product) AS total_price_count FROM `data analytics dataset`;
SELECT OrderID, count(*) AS duplicate_count FROM `data analytics dataset` group by OrderID having count(*) > 1;
SELECT * FROM `data analytics dataset` where UnitPrice <= 0 or TotalPrice <= 0;
SELECT OrderID, CustomerID, Product, TotalPrice FROM `data analytics dataset` order by TotalPrice DESC limit 5;
SELECT avg(Quantity) AS average_quantity_per_order FROM `data analytics dataset`;
SELECT count(DISTINCT CustomerID) AS unique_customers FROM `data analytics dataset`;
SELECT count(DISTINCT Product) AS unique_products FROM `data analytics dataset`;
